# Generated by Django 2.1.4 on 2019-01-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formateurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('profile', models.ImageField(blank=True, upload_to='profile')),
                ('citation', models.CharField(max_length=50)),
            ],
        ),
    ]
