# Generated by Django 2.1.3 on 2018-12-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='debugger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_debug', models.CharField(max_length=50)),
                ('cours_debug', models.TextField(blank=True, help_text='Introduction du cours', max_length=300)),
                ('image_debug', models.ImageField(blank=True, upload_to='')),
                ('cours_debug_2', models.TextField(blank=True, help_text='Devellopement du cours')),
                ('image_debug_2', models.ImageField(blank=True, upload_to='')),
                ('cours_debug_3', models.TextField(blank=True, help_text='conclusion du cours', max_length=500)),
            ],
        ),
    ]
