# Generated by Django 2.1.3 on 2018-12-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50)),
                ('prix', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='courses')),
                ('resume', models.CharField(help_text='Petit resumé de votre cours', max_length=300)),
                ('auteur', models.CharField(max_length=255)),
                ('image_auteur', models.ImageField(upload_to='auteur')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cours_1', models.TextField(blank=True, help_text='Introduction du cours', max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('cours_2', models.TextField(blank=True, help_text='Devellopement du cours')),
                ('image_2', models.ImageField(blank=True, upload_to='')),
                ('cours_3', models.TextField(blank=True, help_text='conclusion du cours', max_length=500)),
            ],
        ),
    ]
