# Generated by Django 2.1.4 on 2019-01-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50)),
                ('prix', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='courses')),
                ('resume', models.CharField(help_text='Petit resumé de votre cours', max_length=300)),
                ('auteur', models.CharField(max_length=255)),
                ('image_auteur', models.ImageField(upload_to='auteur')),
            ],
        ),
    ]
